-- CR-V4 PHASE 1: COMPLETE MISCONCEPTIONS DATABASE - PART 2 (PHYSICS)
-- 110+ Expert-Validated Student Misconceptions
-- JEE Mains Experts Team - Based on Real Coaching Experience
-- Version: 2.0 COMPLETE
-- Date: December 8, 2025

-- ============================================================================
-- PHYSICS MISCONCEPTIONS (110 Total)
-- Subject Matter Expert: Physics Department
-- Source: NTA Pattern Analysis, HC Verma, Resnick-Halliday, Coaching Research
-- ============================================================================

INSERT INTO misconceptions (concept_id, misconception_text, correction, recovery_strategy, diagnostic_question, severity_level, common_exam_trap) VALUES

-- MECHANICS - MOTION (PHYS_001 to PHYS_003)
('PHYS_001', 'Velocity and speed are the same thing', 'CORRECTION: Speed is magnitude only (scalar). Velocity includes direction (vector).', 'Speed = |velocity|. A car at 60 km/h has speed 60. Velocity could be 60 km/h North.', 'Can an object have constant speed but changing velocity?', 'HIGH', true),
('PHYS_001', 'Heavier objects fall faster than lighter objects', 'CORRECTION: In vacuum, all objects fall with same acceleration g ≈ 9.8 m/s²', 'Galileo proving: F = mg, a = F/m = g. Mass cancels. Air resistance causes differences.', 'A feather and lead ball in vacuum - which hits ground first?', 'HIGH', true),
('PHYS_001', 'Negative velocity means slowing down', 'CORRECTION: Negative velocity means moving in negative direction. Slowing down depends on acceleration sign.', 'If velocity and acceleration have opposite signs, object slows. Same signs = speeding up.', 'Object with v = -10 m/s and a = -2 m/s². Speeding up or slowing down?', 'HIGH', true),
('PHYS_001', 'At maximum height, acceleration is zero', 'CORRECTION: At max height, VELOCITY is zero, but acceleration remains g (downward)', 'Gravity never turns off. a = g always near Earth surface. Only v becomes momentarily zero.', 'Ball thrown up: what is acceleration at highest point?', 'HIGH', true),
('PHYS_002', 'Projectile motion: horizontal and vertical motions affect each other', 'CORRECTION: Horizontal and vertical motions are INDEPENDENT (superposition principle)', 'Analyze separately: horizontal has a=0, vertical has a=g. Time connects them.', 'Ball dropped vs ball thrown horizontally from same height - which lands first?', 'HIGH', true),
('PHYS_002', 'Maximum range is at θ = 90°', 'CORRECTION: Maximum range is at θ = 45° (for level ground, no air resistance)', 'R = u²sin2θ/g. Maximum when sin2θ = 1, i.e., 2θ = 90°, so θ = 45°.', 'At what angle should a ball be thrown for maximum range?', 'HIGH', true),
('PHYS_003', 'Relative velocity is always the difference of velocities', 'CORRECTION: Relative velocity VAB = VA - VB (vector subtraction)', 'For objects moving in same direction: |VAB| = |VA - VB|. Opposite: |VAB| = |VA| + |VB|.', 'Two trains at 60 km/h in opposite directions: relative speed?', 'MEDIUM', true),

-- MECHANICS - FORCES (PHYS_004 to PHYS_007)
('PHYS_004', 'A moving object must have a force acting on it', 'CORRECTION: Newton 1st Law: constant velocity = ZERO net force', 'Force causes CHANGE in motion (acceleration). No force = no change in velocity.', 'Hockey puck sliding on frictionless ice - is there a force?', 'HIGH', true),
('PHYS_004', 'Action and reaction act on the same body', 'CORRECTION: Action and reaction ALWAYS act on DIFFERENT bodies', 'N3L: If A pushes B, B pushes A with equal and opposite force. Different bodies!', 'If Earth pulls you down, what happens to Earth?', 'HIGH', true),
('PHYS_004', 'Net force zero means object is at rest', 'CORRECTION: Net force zero means constant velocity (could be moving at constant speed)', 'Equilibrium includes rest AND uniform motion. F_net = 0 → a = 0 → v = constant.', 'Car moving at constant 60 km/h: what is net force?', 'HIGH', true),
('PHYS_005', 'Friction always opposes motion', 'CORRECTION: Friction opposes RELATIVE motion (or tendency). It can cause motion!', 'When you walk, friction pushes you forward. It opposes slipping, not walking.', 'What makes you walk forward?', 'HIGH', true),
('PHYS_005', 'Static friction = μsN always', 'CORRECTION: Static friction ≤ μsN. It adjusts to balance applied force up to maximum.', 'fs ≤ μsN. At threshold of slipping, fs = μsN (maximum static friction).', 'If μs = 0.5, N = 20N, and you push with 5N, what is friction?', 'HIGH', true),
('PHYS_005', 'Kinetic friction decreases as speed increases', 'CORRECTION: For dry friction, fk = μkN is constant, independent of speed', 'Coefficient μk is constant. Kinetic friction does not depend on velocity (ideally).', 'If object slides faster, does friction change?', 'MEDIUM', false),
('PHYS_006', 'Centrifugal force is real and points outward', 'CORRECTION: Centrifugal is fictitious (non-inertial frame). Centripetal is real (inward).', 'In inertial frame: only centripetal force exists (toward center). Centrifugal appears in rotating frame.', 'In inertial frame, which is real: centripetal or centrifugal?', 'HIGH', true),
('PHYS_006', 'Centripetal force is a new type of force', 'CORRECTION: Centripetal force is provided by other forces (tension, gravity, friction, etc.)', 'Centripetal = any force directed toward center. Its the role, not the source.', 'In car turning, what provides centripetal force?', 'HIGH', true),
('PHYS_006', 'Centripetal acceleration changes speed', 'CORRECTION: Centripetal acceleration is perpendicular to velocity - only changes direction', 'ac = v²/r points toward center. Perpendicular force does no work, cant change speed.', 'In uniform circular motion, does speed change?', 'HIGH', true),
('PHYS_007', 'g is constant everywhere on Earth', 'CORRECTION: g varies with altitude and latitude. g ≈ 9.8 m/s² is average at surface.', 'g = GM/r². Changes with distance from center. Also varies due to Earths rotation.', 'Is g the same at poles and equator?', 'MEDIUM', true),
('PHYS_007', 'Weight and mass are the same', 'CORRECTION: Mass is amount of matter (constant). Weight is force due to gravity (varies).', 'W = mg. On Moon, mass same, but weight is 1/6th of Earth weight.', 'What is your weight on the Moon?', 'HIGH', true),

-- MECHANICS - ENERGY & MOMENTUM (PHYS_008 to PHYS_011)
('PHYS_008', 'Work = Force × Distance always', 'CORRECTION: Work = Force × Distance × cos(θ) where θ is angle between F and d', 'Only component of force along displacement does work. Perpendicular force does zero work.', 'If you carry a box horizontally, do you do work against gravity?', 'HIGH', true),
('PHYS_008', 'Work done by friction is always negative', 'CORRECTION: Work by friction is negative when opposing motion, but can be positive when aiding motion', 'When friction causes you to walk forward, it does positive work on you.', 'When does friction do positive work?', 'MEDIUM', true),
('PHYS_009', 'Power = Work always', 'CORRECTION: Power = Work/Time = Rate of doing work', 'Power is measured in Watts (J/s). Same work in less time = more power.', 'Two motors do same work. One takes 2s, other 4s. Which has more power?', 'HIGH', true),
('PHYS_010', 'Momentum is lost in inelastic collisions', 'CORRECTION: Momentum is ALWAYS conserved. Kinetic energy is lost in inelastic collisions.', 'Before = After for momentum. KE can convert to heat/deformation, but p is conserved.', 'In inelastic collision, is momentum conserved?', 'HIGH', true),
('PHYS_010', 'Heavier object has more momentum', 'CORRECTION: Momentum = mass × velocity. Depends on both.', 'Light fast object can have more momentum than heavy slow object.', 'Which has more momentum: 1kg at 10m/s or 2kg at 4m/s?', 'MEDIUM', true),
('PHYS_011', 'In elastic collision, velocities are exchanged always', 'CORRECTION: Velocities are exchanged only for equal mass elastic collision', 'For unequal masses, both velocities change. Use conservation of momentum and KE.', 'A 1kg ball at 5m/s hits stationary 2kg ball elastically. Final velocities?', 'MEDIUM', true),
('PHYS_011', 'Impulse = momentum', 'CORRECTION: Impulse = CHANGE in momentum. J = Δp = mv₂ - mv₁', 'Impulse is force × time acting on object. It causes change in momentum.', 'A ball bounces back. Impulse is zero since it returns?', 'HIGH', true),

-- ROTATIONAL MOTION (PHYS_012 to PHYS_015)
('PHYS_012', 'Torque = Force always', 'CORRECTION: Torque = Force × perpendicular distance from axis = r × F × sin(θ)', 'Torque depends on where and how force is applied. Larger r = larger torque.', 'Where should you push a door to open easily?', 'HIGH', true),
('PHYS_012', 'Angular velocity and linear velocity are the same', 'CORRECTION: ω is angular velocity (rad/s). v = rω relates linear and angular.', 'All points on rigid body have same ω. Points farther from axis have larger v.', 'On spinning disc, which moves faster: center or edge?', 'HIGH', true),
('PHYS_013', 'Moment of inertia equals mass', 'CORRECTION: I = Σmr². Depends on mass AND distribution of mass from axis.', 'Same mass, different shape = different I. Hollow cylinder has more I than solid.', 'Ring vs disc of same mass and radius: which has more I?', 'HIGH', true),
('PHYS_013', 'Moment of inertia is same for all axes', 'CORRECTION: I depends on axis of rotation. Different axes give different I.', 'Parallel axis theorem: I = Icm + md². Perpendicular axis theorem for 2D objects.', 'What is I of rod about its end vs center?', 'HIGH', true),
('PHYS_014', 'Angular momentum is always conserved', 'CORRECTION: Angular momentum is conserved only when net external TORQUE is zero', 'L = Iω = constant when τ_ext = 0. External forces dont matter if torque is zero.', 'Ice skater pulls arms in: does L change?', 'HIGH', true),
('PHYS_015', 'Rolling = sliding + rotating combined', 'CORRECTION: In pure rolling, v_cm = Rω (no sliding at contact point)', 'Point of contact has zero velocity relative to surface. Otherwise its sliding.', 'In pure rolling, what is velocity of bottommost point?', 'HIGH', true),

-- THERMODYNAMICS (PHYS_016 to PHYS_022)
('PHYS_016', 'Heat and temperature are the same', 'CORRECTION: Temperature is measure of average KE. Heat is energy transfer due to temperature difference.', 'Hot object has high temperature. Heat flows from hot to cold until equilibrium.', 'Can two objects have same heat?', 'HIGH', true),
('PHYS_016', 'Cold objects contain cold', 'CORRECTION: There is no cold. Cold objects just have less thermal energy.', 'Heat flows from hot to cold. Cold objects absorb heat, not emit cold.', 'How does a refrigerator work?', 'MEDIUM', false),
('PHYS_017', 'All materials expand when heated', 'CORRECTION: Most materials expand, but water contracts from 0-4°C (anomalous expansion)', 'Water is most dense at 4°C. Ice floats because it expands.', 'Why does ice float on water?', 'MEDIUM', true),
('PHYS_018', 'Temperature always rises when heat is added', 'CORRECTION: During phase change (melting, boiling), temperature remains constant despite heat input', 'Latent heat goes into breaking molecular bonds, not increasing KE.', 'What happens to temperature while ice melts at 0°C?', 'HIGH', true),
('PHYS_019', 'ΔU is always positive when heat is added', 'CORRECTION: ΔU = Q - W. If system does work greater than Q, ΔU can be negative.', 'First law: Q = ΔU + W. Internal energy depends on both heat and work.', 'In isothermal process, what is ΔU?', 'HIGH', true),
('PHYS_019', 'Work done by gas is always positive', 'CORRECTION: Work W = PΔV. Positive for expansion, negative for compression.', 'Gas does positive work when expanding. Work is done ON gas when compressed.', 'In compression, is W positive or negative?', 'HIGH', true),
('PHYS_020', 'Second law says entropy always increases', 'CORRECTION: Entropy of UNIVERSE increases. Local decreases are possible with larger increase elsewhere.', 'Refrigerator decreases entropy inside but increases it outside (net increase).', 'How can entropy decrease in refrigerator?', 'MEDIUM', true),
('PHYS_020', 'Heat can flow from cold to hot spontaneously', 'CORRECTION: Heat NEVER flows spontaneously from cold to hot. Requires external work.', 'Second law: natural direction is hot → cold. Reverse requires energy input.', 'Can heat ever flow from cold to hot?', 'HIGH', true),
('PHYS_021', 'KE of gas molecule is kT', 'CORRECTION: Average KE per molecule = (3/2)kT for monatomic ideal gas', 'Each degree of freedom contributes (1/2)kT. Monatomic has 3 translational DOF.', 'What is average KE of molecule at temperature T?', 'HIGH', true),
('PHYS_022', 'Carnot engine has 100% efficiency', 'CORRECTION: Carnot efficiency = 1 - Tc/Th < 100% when Tc > 0', 'No real engine can be 100% efficient. Carnot is upper limit for given temperatures.', 'What is efficiency of Carnot engine between 600K and 300K?', 'HIGH', true),

-- ELECTROSTATICS (PHYS_024 to PHYS_031)
('PHYS_024', 'Like charges attract', 'CORRECTION: Like charges REPEL. Unlike charges attract.', 'Coulombs law: F = kq₁q₂/r². Same sign → positive F → repulsion.', 'What happens when two positive charges approach?', 'HIGH', true),
('PHYS_024', 'Coulombs law works at any distance', 'CORRECTION: Coulombs law requires point charges or spherical distributions. Fails for extended charges.', 'For large charged objects close together, must use integration.', 'Does Coulombs law apply to two charged spheres touching?', 'MEDIUM', false),
('PHYS_025', 'Electric field at center of charged ring is maximum', 'CORRECTION: Electric field at CENTER of ring is ZERO (symmetry cancellation)', 'All field components cancel due to symmetry. Maximum is at certain distance on axis.', 'What is E at center of uniformly charged ring?', 'HIGH', true),
('PHYS_025', 'Electric field and electric force always point same direction', 'CORRECTION: For positive charge: same direction. For negative charge: opposite directions.', 'F = qE. If q < 0, F is opposite to E.', 'Electron in field pointing right moves which way?', 'HIGH', true),
('PHYS_026', 'Gausss law tells us E at any point', 'CORRECTION: Gauss law gives net flux through surface. E can only be found using symmetry.', 'φ = ∮E·dA = q_enc/ε₀. Need high symmetry (sphere, cylinder, plane) to extract E.', 'Can Gauss law find E for arbitrary charge distribution?', 'MEDIUM', true),
('PHYS_027', 'Potential and potential energy are the same', 'CORRECTION: V = U/q. Potential is energy per unit charge. PE is qV.', 'Potential is property of field. PE depends on charge placed in field.', 'What is SI unit of potential? Of potential energy?', 'HIGH', true),
('PHYS_027', 'Electric potential is always positive', 'CORRECTION: Potential can be negative (near negative charges)', 'V = kQ/r. If Q < 0, V < 0. Potential is zero at infinity by convention.', 'What is the sign of potential near an electron?', 'MEDIUM', true),
('PHYS_028', 'Capacitance depends on charge stored', 'CORRECTION: C = Q/V. Capacitance is constant for given geometry.', 'C depends only on geometry and medium. Q and V change together, C stays same.', 'If we double the charge on capacitor, does C double?', 'HIGH', true),
('PHYS_028', 'Capacitors in series add up like resistors in parallel', 'CORRECTION: Series: 1/C_eq = 1/C₁ + 1/C₂. Parallel: C_eq = C₁ + C₂.', 'Capacitors add opposite to resistors. Series decreases, parallel increases.', 'Two 4μF capacitors in series: net capacitance?', 'HIGH', true),
('PHYS_029', 'Energy stored is QV', 'CORRECTION: Energy = (1/2)QV = (1/2)CV² = Q²/2C', 'Factor of 1/2 because V builds up as we add charge. Average V is V/2.', 'What is energy stored in 4μF capacitor at 100V?', 'HIGH', true),
('PHYS_030', 'Electric field inside conductor is due to external charges', 'CORRECTION: E inside conductor is ZERO in electrostatic equilibrium (charges redistribute)', 'Free electrons move until internal field cancels external. Net E inside = 0.', 'What is E inside a metal sphere in external field?', 'HIGH', true),
('PHYS_031', 'Earthing makes object positive', 'CORRECTION: Earthing brings object to ground potential (usually zero). Charges flow to/from Earth.', 'Earth is infinite reservoir. Object gains or loses electrons to reach ground potential.', 'Negatively charged sphere is earthed. What happens?', 'MEDIUM', false),

-- CURRENT ELECTRICITY (PHYS_032 to PHYS_038)
('PHYS_032', 'Electrons flow from positive to negative terminal', 'CORRECTION: Electrons flow from NEGATIVE to POSITIVE. Conventional current is opposite.', 'Conventional current: + to -. Electron flow: - to +. Historical convention.', 'In which direction do electrons flow in a wire?', 'HIGH', true),
('PHYS_033', 'Resistance depends on current', 'CORRECTION: R = ρL/A. Resistance is property of wire, independent of current (for ohmic materials)', 'For ohmic materials, R is constant. V = IR with R fixed.', 'If current doubles, does resistance double?', 'HIGH', true),
('PHYS_033', 'Ohms Law always applies', 'CORRECTION: Ohms Law applies only to OHMIC materials with linear V-I relationship', 'Diodes, LEDs, filaments are non-ohmic. R varies with voltage.', 'Does Ohms Law apply to a diode?', 'MEDIUM', true),
('PHYS_034', 'Kirchhoffs voltage law: ΣV = I × R_total', 'CORRECTION: KVL: ΣV = 0 around closed loop. Sum of voltage rises = sum of drops.', 'Go around loop, add EMFs with signs, subtract IR drops. Net = 0.', 'In a loop with 10V battery and 2Ω, 3Ω resistors in series with 2A, verify KVL.', 'HIGH', true),
('PHYS_034', 'Current takes the path of least resistance', 'CORRECTION: Current flows through ALL available paths, with more going through lower resistance', 'Current divides inversely as resistance in parallel. Not just one path.', 'In parallel 2Ω and 4Ω, how does 3A divide?', 'HIGH', true),
('PHYS_035', 'EMF and terminal voltage are always equal', 'CORRECTION: V = ε - Ir. Terminal voltage equals EMF only when no current flows (open circuit)', 'Internal resistance causes voltage drop inside battery.', 'A 12V battery with 1Ω internal resistance delivers 2A. Terminal voltage?', 'HIGH', true),
('PHYS_036', 'Potentiometer measures current', 'CORRECTION: Potentiometer compares EMFs. It draws zero current at balance point.', 'At null point, no current in galvanometer. Used for accurate EMF comparison.', 'Why is potentiometer preferred over voltmeter?', 'MEDIUM', true),
('PHYS_037', 'Wheatstone bridge is balanced when all resistances are equal', 'CORRECTION: Balanced when P/Q = R/S (ratios equal, not absolute values)', 'Balance condition is ratio equality. P=Q=R=S is just one solution.', 'Is bridge balanced with P=2, Q=4, R=3, S=6?', 'HIGH', true),
('PHYS_038', 'Galvanometer directly measures current in amperes', 'CORRECTION: Galvanometer gives deflection proportional to current. Needs calibration.', 'Convert to ammeter with shunt. Convert to voltmeter with high resistance.', 'How do you convert galvanometer to ammeter?', 'MEDIUM', false),

-- MAGNETISM & EMI (PHYS_039 to PHYS_045)
('PHYS_039', 'Magnetic force on stationary charge exists', 'CORRECTION: F = qv×B. If v = 0, F = 0. Magnetic force only on moving charges.', 'Magnetic force is velocity-dependent. Electric force works on stationary charges.', 'Stationary proton in magnetic field: what force?', 'HIGH', true),
('PHYS_040', 'Magnetic field lines are closed because they start and end on poles', 'CORRECTION: Lines dont start/end anywhere. They form continuous closed loops.', 'No magnetic monopoles exist. Lines go from N to S outside, S to N inside.', 'Where do magnetic field lines start?', 'MEDIUM', true),
('PHYS_041', 'Biot-Savart law gives total field from a wire segment', 'CORRECTION: It gives contribution dB from element Idl. Integrate for total field.', 'dB = (μ₀/4π)(Idl×r̂)/r². Must integrate along entire current.', 'Field at center of semicircular wire?', 'MEDIUM', true),
('PHYS_042', 'Amperes law works for any current configuration', 'CORRECTION: Like Gauss law, Ampere law needs high symmetry to extract B from ∮B·dl', 'Works well for infinite wire, solenoid, toroid. Not for arbitrary shapes.', 'Can Amperes law find B for finite straight wire?', 'MEDIUM', false),
('PHYS_043', 'EMF is induced when there is magnetic field', 'CORRECTION: EMF is induced only when FLUX CHANGES. Static field = no EMF.', 'Faradays law: ε = -dφ/dt. Change in flux required, not just presence of field.', 'Coil in constant magnetic field: any EMF?', 'HIGH', true),
('PHYS_044', 'Lenzs law says induced current opposes the field', 'CORRECTION: Induced current opposes the CHANGE in flux, not the field itself', 'If flux increases, induced current creates field to oppose increase (not the original field).', 'Magnet approaching coil: direction of induced current?', 'HIGH', true),
('PHYS_045', 'Self inductance depends on current', 'CORRECTION: L depends only on geometry. L = φ/I where both φ and I change proportionally.', 'L = μ₀n²Al for solenoid. Independent of current.', 'If current doubles, does inductance double?', 'HIGH', true),
('PHYS_034', 'Magnetic force can change speed of charged particle', 'CORRECTION: F = qv×B is perpendicular to v, so no work is done, speed stays constant', 'W = F·d = 0 (perpendicular). Only direction changes, not speed.', 'Can magnetic field accelerate charged particle from rest?', 'HIGH', true),

-- AC CIRCUITS (PHYS_046 to PHYS_048)
('PHYS_046', 'In AC, V = IR works with peak values', 'CORRECTION: V_rms = I_rms × Z. Use rms values for power calculations.', 'V₀ = I₀Z works for peak. Power = V_rms × I_rms × cos(φ).', 'AC supply: 220V rating is rms or peak?', 'HIGH', true),
('PHYS_046', 'Phase difference in AC is always 90°', 'CORRECTION: Phase depends on component. R: 0°, L: 90° lead, C: 90° lag.', 'In RLC circuit, net phase depends on relative values of XL and XC.', 'In pure inductor, voltage leads or lags current?', 'HIGH', true),
('PHYS_047', 'At resonance, current is zero', 'CORRECTION: At resonance, current is MAXIMUM (XL = XC, Z is minimum)', 'Resonance: XL = XC, so Z = R (minimum). Maximum current flows.', 'What happens to current at LCR resonance?', 'HIGH', true),
('PHYS_047', 'Resonance frequency depends on R', 'CORRECTION: f₀ = 1/(2π√LC). Resistance does not affect resonance frequency.', 'R affects sharpness (Q factor) but not the resonance frequency.', 'If R doubles, does resonance frequency change?', 'HIGH', true),
('PHYS_048', 'Transformers work with DC', 'CORRECTION: Transformers only work with AC. DC gives constant flux = no induced EMF.', 'Faradays law needs changing flux. DC steady state = no induction.', 'Can transformer step up DC voltage?', 'HIGH', true),
('PHYS_048', 'Transformer changes power', 'CORRECTION: Ideal transformer conserves power: P_in = P_out. V₁I₁ = V₂I₂.', 'Step-up increases V, decreases I. Step-down opposite. Power constant.', 'If transformer doubles voltage, what happens to current?', 'HIGH', true),

-- OPTICS (PHYS_049 to PHYS_055)
('PHYS_049', 'Image distance equals object distance for plane mirror', 'CORRECTION: Image appears at same distance BEHIND mirror as object is in front', 'Virtual image, same size, laterally inverted. Distance measured from mirror.', 'Object 30cm from plane mirror: where is image?', 'MEDIUM', true),
('PHYS_049', 'Real images are always upright', 'CORRECTION: Real images are INVERTED. Virtual images are upright.', 'Real: rays actually converge. Virtual: rays appear to diverge from image point.', 'Is the image in a camera real or virtual?', 'HIGH', true),
('PHYS_050', 'Lens power and focal length are the same', 'CORRECTION: Power P = 1/f (in meters). P in diopters when f in meters.', 'Short focal length = high power (more bending). Long f = low P.', 'If f = 25cm, what is power?', 'HIGH', true),
('PHYS_050', 'Thick lens is more powerful', 'CORRECTION: For same material and radii, thicker lens means shorter f and more power, but shape matters.', 'Power depends on curvature of surfaces. More curved = more power.', 'Which is more powerful: flat lens or curved lens?', 'MEDIUM', false),
('PHYS_051', 'Light always bends toward normal when entering denser medium', 'CORRECTION: Correct! But when going to rarer medium, it bends away from normal.', 'Snells law: n₁sinθ₁ = n₂sinθ₂. Higher n = slower speed = bends toward normal.', 'Light going from glass to air: toward or away from normal?', 'HIGH', true),
('PHYS_051', 'TIR occurs when going from rarer to denser medium', 'CORRECTION: TIR only when light goes from DENSER to RARER medium at angle > critical angle', 'Critical angle exists only when n₁ > n₂. Then sinθc = n₂/n₁.', 'Can TIR happen when light goes from air to glass?', 'HIGH', true),
('PHYS_052', 'Microscope magnification = telescope magnification', 'CORRECTION: Different formulas. Microscope: m = v/u × D/fe. Telescope: m = fo/fe.', 'Microscope magnifies small close objects. Telescope magnifies distant objects.', 'Why cant a microscope see stars?', 'MEDIUM', false),
('PHYS_053', 'Light always travels in straight lines', 'CORRECTION: Light diffracts around obstacles and bends at interfaces (refraction)', 'Wave nature allows bending. Ray optics is approximation for large obstacles.', 'Why can we hear around corners but not see?', 'HIGH', true),
('PHYS_054', 'In double slit, dark fringe means no light', 'CORRECTION: Dark fringe is MINIMUM intensity due to destructive interference, but some light present', 'Complete darkness only when amplitudes exactly equal. Usually some residual.', 'Is intensity exactly zero at dark fringes?', 'MEDIUM', true),
('PHYS_054', 'Path difference for bright fringe is nλ', 'CORRECTION: Correct for maxima: path diff = nλ. For minima: (n + 1/2)λ.', 'Constructive: waves in phase. Destructive: waves 180° out of phase.', 'Path difference for 3rd bright fringe?', 'HIGH', true),
('PHYS_055', 'Polarization proves light is longitudinal', 'CORRECTION: Polarization proves light is TRANSVERSE. Only transverse waves can be polarized.', 'Sound (longitudinal) cannot be polarized. Light polarization confirms transverse nature.', 'Can sound waves be polarized?', 'HIGH', true);

COMMIT;
