-- CR-V4 PHASE 1 V2: PRODUCTION CONCEPT SEEDS
-- 165 JEE Concepts with NEP 2025 Compliance
-- Version: 2.0 (Council Approved)
-- Date: December 8, 2025

-- ====== MATHEMATICS (55 CONCEPTS) ======

INSERT INTO concepts (id, name, subject, difficulty, mastery_time_hours, exam_weightage, nta_frequency_score, syllabus_status, competency_type, nep_verified) VALUES
('MATH_001', 'Number System', 'MATHEMATICS', 0.30, 3, 2.0, 8, 'ACTIVE', 'ROTE_MEMORY', true),
('MATH_002', 'Sets & Relations', 'MATHEMATICS', 0.35, 4, 2.0, 7, 'ACTIVE', 'APPLICATION', true),
('MATH_003', 'Number Theory', 'MATHEMATICS', 0.40, 5, 1.0, 5, 'ACTIVE', 'CRITICAL_THINKING', true),
('MATH_004', 'Linear Equations', 'MATHEMATICS', 0.45, 6, 3.0, 9, 'ACTIVE', 'APPLICATION', true),
('MATH_005', 'Quadratic Equations', 'MATHEMATICS', 0.50, 7, 4.0, 10, 'ACTIVE', 'APPLICATION', true),
('MATH_006', 'Inequalities', 'MATHEMATICS', 0.40, 5, 2.0, 6, 'ACTIVE', 'APPLICATION', true),
('MATH_007', 'Permutations & Combinations', 'MATHEMATICS', 0.55, 8, 3.0, 8, 'ACTIVE', 'CRITICAL_THINKING', true),
('MATH_008', 'Probability', 'MATHEMATICS', 0.60, 9, 3.0, 8, 'ACTIVE', 'CRITICAL_THINKING', true),
('MATH_009', 'Mathematical Induction', 'MATHEMATICS', 0.50, 6, 0.0, 0, 'NEP_REMOVED', NULL, true),
('MATH_010', 'Binomial Theorem', 'MATHEMATICS', 0.55, 7, 2.0, 7, 'ACTIVE', 'APPLICATION', true),
('MATH_011', 'Complex Numbers', 'MATHEMATICS', 0.50, 6, 2.0, 7, 'ACTIVE', 'APPLICATION', true),
('MATH_012', 'Mathematical Reasoning', 'MATHEMATICS', 0.40, 5, 0.0, 0, 'NEP_REMOVED', NULL, true),
('MATH_013', 'Trigonometric Ratios', 'MATHEMATICS', 0.35, 4, 3.0, 9, 'ACTIVE', 'ROTE_MEMORY', true),
('MATH_014', 'Trigonometric Identities', 'MATHEMATICS', 0.45, 6, 3.0, 8, 'ACTIVE', 'APPLICATION', true),
('MATH_015', 'Inverse Trigonometry', 'MATHEMATICS', 0.50, 7, 2.0, 7, 'ACTIVE', 'APPLICATION', true),
('MATH_016', 'Compound Angles', 'MATHEMATICS', 0.55, 8, 2.0, 6, 'ACTIVE', 'CRITICAL_THINKING', true),
('MATH_017', 'Height & Distance', 'MATHEMATICS', 0.40, 5, 1.0, 5, 'ACTIVE', 'APPLICATION', true),
('MATH_018', 'General Solutions', 'MATHEMATICS', 0.50, 6, 1.0, 4, 'ACTIVE', 'APPLICATION', true),
('MATH_019', 'Arithmetic Progression', 'MATHEMATICS', 0.35, 4, 2.0, 6, 'ACTIVE', 'APPLICATION', true),
('MATH_020', 'Geometric Progression', 'MATHEMATICS', 0.40, 5, 2.0, 6, 'ACTIVE', 'APPLICATION', true),
('MATH_021', 'Harmonic Progression', 'MATHEMATICS', 0.45, 6, 1.0, 4, 'ACTIVE', 'APPLICATION', true),
('MATH_022', 'Sum Formulas & AGP', 'MATHEMATICS', 0.50, 6, 1.0, 4, 'ACTIVE', 'CRITICAL_THINKING', true),
('MATH_023', 'Distance & Section Formula', 'MATHEMATICS', 0.30, 3, 1.0, 5, 'ACTIVE', 'ROTE_MEMORY', true),
('MATH_024', 'Straight Line', 'MATHEMATICS', 0.45, 6, 4.0, 9, 'ACTIVE', 'APPLICATION', true),
('MATH_025', 'Pair of Lines', 'MATHEMATICS', 0.50, 7, 2.0, 6, 'ACTIVE', 'APPLICATION', true),
('MATH_026', 'Circle', 'MATHEMATICS', 0.50, 8, 3.0, 8, 'ACTIVE', 'APPLICATION', true),
('MATH_027', 'Parabola', 'MATHEMATICS', 0.55, 8, 2.0, 6, 'ACTIVE', 'CRITICAL_THINKING', true),
('MATH_028', 'Ellipse', 'MATHEMATICS', 0.55, 8, 2.0, 6, 'ACTIVE', 'CRITICAL_THINKING', true),
('MATH_029', 'Hyperbola', 'MATHEMATICS', 0.55, 8, 1.0, 4, 'ACTIVE', 'CRITICAL_THINKING', true),
('MATH_030', 'Parametric Forms', 'MATHEMATICS', 0.50, 6, 1.0, 3, 'ACTIVE', 'APPLICATION', true),
('MATH_031', 'Reflection Geometry', 'MATHEMATICS', 0.45, 5, 1.0, 3, 'ACTIVE', 'APPLICATION', true),
('MATH_032', 'Conic Sections (General)', 'MATHEMATICS', 0.60, 9, 1.0, 3, 'ACTIVE', 'CRITICAL_THINKING', true),
('MATH_033', 'Limits', 'MATHEMATICS', 0.45, 6, 2.0, 7, 'ACTIVE', 'APPLICATION', true),
('MATH_034', 'Continuity', 'MATHEMATICS', 0.45, 6, 1.0, 5, 'ACTIVE', 'APPLICATION', true),
('MATH_035', 'Differentiability', 'MATHEMATICS', 0.50, 7, 1.0, 4, 'ACTIVE', 'APPLICATION', true),
('MATH_036', 'Derivatives (Basic)', 'MATHEMATICS', 0.40, 5, 3.0, 9, 'ACTIVE', 'APPLICATION', true),
('MATH_037', 'Chain Rule', 'MATHEMATICS', 0.50, 7, 2.0, 7, 'ACTIVE', 'APPLICATION', true),
('MATH_038', 'Implicit Differentiation', 'MATHEMATICS', 0.55, 8, 2.0, 6, 'ACTIVE', 'CRITICAL_THINKING', true),
('MATH_039', 'Applications of Derivatives', 'MATHEMATICS', 0.55, 8, 4.0, 9, 'ACTIVE', 'CRITICAL_THINKING', true),
('MATH_040', 'Maxima & Minima', 'MATHEMATICS', 0.60, 9, 3.0, 8, 'ACTIVE', 'CRITICAL_THINKING', true),
('MATH_041', 'Indefinite Integration', 'MATHEMATICS', 0.45, 6, 2.0, 7, 'ACTIVE', 'APPLICATION', true),
('MATH_042', 'Integration Substitution', 'MATHEMATICS', 0.55, 8, 2.0, 6, 'ACTIVE', 'CRITICAL_THINKING', true),
('MATH_043', 'Integration by Parts', 'MATHEMATICS', 0.55, 8, 2.0, 6, 'ACTIVE', 'CRITICAL_THINKING', true),
('MATH_044', 'Partial Fractions', 'MATHEMATICS', 0.50, 7, 1.0, 4, 'ACTIVE', 'APPLICATION', true),
('MATH_045', 'Definite Integration', 'MATHEMATICS', 0.50, 7, 3.0, 8, 'ACTIVE', 'APPLICATION', true),
('MATH_046', 'Properties of Definite Integral', 'MATHEMATICS', 0.55, 8, 2.0, 6, 'ACTIVE', 'CRITICAL_THINKING', true),
('MATH_047', 'Area under Curves', 'MATHEMATICS', 0.55, 8, 3.0, 8, 'ACTIVE', 'CRITICAL_THINKING', true),
('MATH_048', 'Differential Equations', 'MATHEMATICS', 0.60, 10, 2.0, 6, 'ACTIVE', 'CRITICAL_THINKING', true),
('MATH_049', 'Variable Separable', 'MATHEMATICS', 0.50, 7, 1.0, 4, 'ACTIVE', 'APPLICATION', true),
('MATH_050', 'Linear Differential Equations', 'MATHEMATICS', 0.55, 8, 1.0, 3, 'ACTIVE', 'CRITICAL_THINKING', true),
('MATH_051', 'Vector Algebra', 'MATHEMATICS', 0.40, 5, 2.0, 6, 'ACTIVE', 'APPLICATION', true),
('MATH_052', 'Dot Product & Cross Product', 'MATHEMATICS', 0.50, 7, 2.0, 6, 'ACTIVE', 'APPLICATION', true),
('MATH_053', 'Scalar Triple Product', 'MATHEMATICS', 0.55, 8, 1.0, 3, 'ACTIVE', 'CRITICAL_THINKING', true),
('MATH_054', '3D Geometry (Lines & Planes)', 'MATHEMATICS', 0.50, 8, 2.0, 6, 'ACTIVE', 'APPLICATION', true),
('MATH_055', 'Distance in 3D', 'MATHEMATICS', 0.50, 7, 1.0, 3, 'ACTIVE', 'APPLICATION', true);

-- ====== PHYSICS (55 CONCEPTS) ======

INSERT INTO concepts (id, name, subject, difficulty, mastery_time_hours, exam_weightage, nta_frequency_score, syllabus_status, competency_type, nep_verified) VALUES
('PHYS_001', 'Motion in 1D', 'PHYSICS', 0.40, 5, 3.0, 9, 'ACTIVE', 'APPLICATION', true),
('PHYS_002', 'Motion in 2D', 'PHYSICS', 0.45, 6, 3.0, 8, 'ACTIVE', 'APPLICATION', true),
('PHYS_003', 'Relative Motion', 'PHYSICS', 0.45, 6, 2.0, 6, 'ACTIVE', 'APPLICATION', true),
('PHYS_004', 'Newton''s Laws', 'PHYSICS', 0.50, 8, 4.0, 10, 'ACTIVE', 'CRITICAL_THINKING', true),
('PHYS_005', 'Forces & Friction', 'PHYSICS', 0.50, 8, 3.0, 8, 'ACTIVE', 'APPLICATION', true),
('PHYS_006', 'Circular Motion', 'PHYSICS', 0.60, 10, 4.0, 9, 'ACTIVE', 'CRITICAL_THINKING', true),
('PHYS_007', 'Gravitation', 'PHYSICS', 0.55, 9, 3.0, 7, 'ACTIVE', 'CRITICAL_THINKING', true),
('PHYS_008', 'Work & Energy', 'PHYSICS', 0.50, 8, 4.0, 9, 'ACTIVE', 'APPLICATION', true),
('PHYS_009', 'Power & Energy', 'PHYSICS', 0.45, 6, 2.0, 6, 'ACTIVE', 'APPLICATION', true),
('PHYS_010', 'Conservation of Momentum', 'PHYSICS', 0.55, 9, 3.0, 8, 'ACTIVE', 'CRITICAL_THINKING', true),
('PHYS_011', 'Collision & Impulse', 'PHYSICS', 0.55, 9, 2.0, 6, 'ACTIVE', 'CRITICAL_THINKING', true),
('PHYS_012', 'Rotational Motion', 'PHYSICS', 0.65, 12, 4.0, 8, 'ACTIVE', 'CRITICAL_THINKING', true),
('PHYS_013', 'Moment of Inertia', 'PHYSICS', 0.60, 10, 3.0, 7, 'ACTIVE', 'CRITICAL_THINKING', true),
('PHYS_014', 'Torque & Angular Momentum', 'PHYSICS', 0.60, 10, 2.0, 6, 'ACTIVE', 'CRITICAL_THINKING', true),
('PHYS_015', 'Rolling Motion', 'PHYSICS', 0.60, 10, 2.0, 5, 'ACTIVE', 'CRITICAL_THINKING', true),
('PHYS_016', 'Heat & Temperature', 'PHYSICS', 0.40, 5, 2.0, 6, 'ACTIVE', 'ROTE_MEMORY', true),
('PHYS_017', 'Thermal Expansion', 'PHYSICS', 0.35, 4, 1.0, 3, 'ACTIVE', 'ROTE_MEMORY', true),
('PHYS_018', 'Calorimetry', 'PHYSICS', 0.45, 6, 2.0, 6, 'ACTIVE', 'APPLICATION', true),
('PHYS_019', 'First Law of Thermodynamics', 'PHYSICS', 0.55, 9, 2.0, 6, 'ACTIVE', 'CRITICAL_THINKING', true),
('PHYS_020', 'Second Law of Thermodynamics', 'PHYSICS', 0.60, 10, 2.0, 5, 'ACTIVE', 'CRITICAL_THINKING', true),
('PHYS_021', 'Kinetic Theory', 'PHYSICS', 0.50, 8, 2.0, 6, 'ACTIVE', 'APPLICATION', true),
('PHYS_022', 'Heat Engines & Cycles', 'PHYSICS', 0.55, 9, 1.0, 3, 'ACTIVE', 'CRITICAL_THINKING', true),
('PHYS_023', 'States of Matter', 'PHYSICS', 0.40, 5, 0.0, 0, 'NEP_REMOVED', NULL, true),
('PHYS_024', 'Coulomb''s Law', 'PHYSICS', 0.45, 6, 2.0, 6, 'ACTIVE', 'APPLICATION', true),
('PHYS_025', 'Electric Field', 'PHYSICS', 0.50, 8, 3.0, 8, 'ACTIVE', 'APPLICATION', true),
('PHYS_026', 'Gauss''s Law', 'PHYSICS', 0.55, 9, 2.0, 5, 'ACTIVE', 'CRITICAL_THINKING', true),
('PHYS_027', 'Electric Potential', 'PHYSICS', 0.55, 9, 3.0, 7, 'ACTIVE', 'CRITICAL_THINKING', true),
('PHYS_028', 'Capacitance & Capacitors', 'PHYSICS', 0.50, 8, 2.0, 6, 'ACTIVE', 'APPLICATION', true),
('PHYS_029', 'Energy in Electric Field', 'PHYSICS', 0.50, 8, 1.0, 3, 'ACTIVE', 'APPLICATION', true),
('PHYS_030', 'Conductors & Insulators', 'PHYSICS', 0.40, 5, 1.0, 3, 'ACTIVE', 'ROTE_MEMORY', true),
('PHYS_031', 'Earthing & Shielding', 'PHYSICS', 0.35, 4, 1.0, 2, 'ACTIVE', 'ROTE_MEMORY', true),
('PHYS_032', 'Drift Velocity', 'PHYSICS', 0.45, 6, 1.0, 3, 'ACTIVE', 'APPLICATION', true),
('PHYS_033', 'Ohm''s Law & Resistance', 'PHYSICS', 0.40, 5, 2.0, 6, 'ACTIVE', 'ROTE_MEMORY', true),
('PHYS_034', 'Kirchhoff''s Laws', 'PHYSICS', 0.50, 8, 3.0, 8, 'ACTIVE', 'APPLICATION', true),
('PHYS_035', 'Emf & Internal Resistance', 'PHYSICS', 0.45, 6, 2.0, 6, 'ACTIVE', 'APPLICATION', true),
('PHYS_036', 'Potentiometer & Meter Bridge', 'PHYSICS', 0.55, 9, 2.0, 5, 'ACTIVE', 'CRITICAL_THINKING', true),
('PHYS_037', 'Wheatstone Bridge', 'PHYSICS', 0.50, 8, 1.0, 3, 'ACTIVE', 'APPLICATION', true),
('PHYS_038', 'Galvanometer & Instruments', 'PHYSICS', 0.50, 8, 1.0, 3, 'ACTIVE', 'APPLICATION', true),
('PHYS_039', 'Magnetic Force on Current', 'PHYSICS', 0.50, 8, 2.0, 6, 'ACTIVE', 'APPLICATION', true),
('PHYS_040', 'Magnetic Field', 'PHYSICS', 0.50, 8, 2.0, 6, 'ACTIVE', 'APPLICATION', true),
('PHYS_041', 'Biot-Savart Law', 'PHYSICS', 0.55, 9, 1.0, 3, 'ACTIVE', 'CRITICAL_THINKING', true),
('PHYS_042', 'Ampere''s Law', 'PHYSICS', 0.55, 9, 1.0, 3, 'ACTIVE', 'CRITICAL_THINKING', true),
('PHYS_043', 'Electromagnetic Induction', 'PHYSICS', 0.60, 10, 3.0, 8, 'ACTIVE', 'CRITICAL_THINKING', true),
('PHYS_044', 'Faraday''s Law & Lenz''s Law', 'PHYSICS', 0.60, 10, 2.0, 6, 'ACTIVE', 'CRITICAL_THINKING', true),
('PHYS_045', 'Inductance & Self-Inductance', 'PHYSICS', 0.55, 9, 1.0, 3, 'ACTIVE', 'CRITICAL_THINKING', true),
('PHYS_046', 'AC Circuits & Phasor Diagrams', 'PHYSICS', 0.60, 10, 2.0, 5, 'ACTIVE', 'CRITICAL_THINKING', true),
('PHYS_047', 'LCR Circuits & Resonance', 'PHYSICS', 0.65, 12, 2.0, 5, 'ACTIVE', 'CRITICAL_THINKING', true),
('PHYS_048', 'Transformers', 'PHYSICS', 0.50, 8, 1.0, 3, 'ACTIVE', 'APPLICATION', true),
('PHYS_049', 'Ray Optics & Mirrors', 'PHYSICS', 0.45, 6, 2.0, 6, 'ACTIVE', 'APPLICATION', true),
('PHYS_050', 'Lens Makers Formula', 'PHYSICS', 0.50, 8, 2.0, 6, 'ACTIVE', 'APPLICATION', true),
('PHYS_051', 'Refraction & TIR', 'PHYSICS', 0.50, 8, 2.0, 6, 'ACTIVE', 'APPLICATION', true),
('PHYS_052', 'Optical Instruments', 'PHYSICS', 0.50, 8, 2.0, 5, 'ACTIVE', 'APPLICATION', true),
('PHYS_053', 'Wave Optics & Huygens', 'PHYSICS', 0.55, 9, 1.0, 3, 'ACTIVE', 'CRITICAL_THINKING', true),
('PHYS_054', 'Double Slit Experiment', 'PHYSICS', 0.55, 9, 2.0, 5, 'ACTIVE', 'CRITICAL_THINKING', true),
('PHYS_055', 'Diffraction & Polarization', 'PHYSICS', 0.60, 10, 1.0, 3, 'ACTIVE', 'CRITICAL_THINKING', true);

-- ====== CHEMISTRY (55 CONCEPTS) ======

INSERT INTO concepts (id, name, subject, difficulty, mastery_time_hours, exam_weightage, nta_frequency_score, syllabus_status, competency_type, nep_verified) VALUES
('CHEM_001', 'Atomic Structure', 'CHEMISTRY', 0.40, 5, 2.0, 6, 'ACTIVE', 'ROTE_MEMORY', true),
('CHEM_002', 'Quantum Numbers', 'CHEMISTRY', 0.45, 6, 1.0, 3, 'ACTIVE', 'APPLICATION', true),
('CHEM_003', 'Periodic Table', 'CHEMISTRY', 0.35, 4, 3.0, 9, 'ACTIVE', 'ROTE_MEMORY', true),
('CHEM_004', 'Chemical Bonding', 'CHEMISTRY', 0.50, 8, 4.0, 9, 'ACTIVE', 'APPLICATION', true),
('CHEM_005', 'Hybridization', 'CHEMISTRY', 0.55, 9, 2.0, 6, 'ACTIVE', 'CRITICAL_THINKING', true),
('CHEM_006', 'Molecular Orbital Theory', 'CHEMISTRY', 0.60, 10, 1.0, 3, 'ACTIVE', 'CRITICAL_THINKING', true),
('CHEM_007', 'Thermodynamics (Basic)', 'CHEMISTRY', 0.50, 8, 2.0, 6, 'ACTIVE', 'APPLICATION', true),
('CHEM_008', 'Hess''s Law', 'CHEMISTRY', 0.50, 8, 1.0, 3, 'ACTIVE', 'APPLICATION', true),
('CHEM_009', 'Entropy & Gibbs Free Energy', 'CHEMISTRY', 0.55, 9, 2.0, 5, 'ACTIVE', 'CRITICAL_THINKING', true),
('CHEM_010', 'Chemical Equilibrium', 'CHEMISTRY', 0.55, 9, 3.0, 8, 'ACTIVE', 'CRITICAL_THINKING', true),
('CHEM_011', 'Ionic Equilibrium', 'CHEMISTRY', 0.60, 10, 4.0, 9, 'ACTIVE', 'CRITICAL_THINKING', true),
('CHEM_012', 'Acid-Base & pH', 'CHEMISTRY', 0.50, 8, 3.0, 8, 'ACTIVE', 'APPLICATION', true),
('CHEM_013', 'Buffer Solutions', 'CHEMISTRY', 0.55, 9, 1.0, 3, 'ACTIVE', 'CRITICAL_THINKING', true),
('CHEM_014', 'Solubility Product', 'CHEMISTRY', 0.55, 9, 2.0, 5, 'ACTIVE', 'CRITICAL_THINKING', true),
('CHEM_015', 'Redox Reactions', 'CHEMISTRY', 0.45, 6, 3.0, 8, 'ACTIVE', 'APPLICATION', true),
('CHEM_016', 'Electrochemistry', 'CHEMISTRY', 0.60, 10, 3.0, 7, 'ACTIVE', 'CRITICAL_THINKING', true),
('CHEM_017', 'Corrosion & Galvanization', 'CHEMISTRY', 0.45, 6, 1.0, 2, 'ACTIVE', 'APPLICATION', true),
('CHEM_018', 'Kinetics & Rate Laws', 'CHEMISTRY', 0.55, 9, 2.0, 5, 'ACTIVE', 'CRITICAL_THINKING', true),
('CHEM_019', 's-Block Elements (Group 1 & 2)', 'CHEMISTRY', 0.45, 6, 3.0, 7, 'ACTIVE', 'APPLICATION', true),
('CHEM_020', 'p-Block Elements (Group 13-18)', 'CHEMISTRY', 0.55, 9, 4.0, 8, 'ACTIVE', 'CRITICAL_THINKING', true),
('CHEM_021', 'Alkali Metals', 'CHEMISTRY', 0.40, 5, 2.0, 5, 'ACTIVE', 'ROTE_MEMORY', true),
('CHEM_022', 'Alkaline Earth Metals', 'CHEMISTRY', 0.40, 5, 1.0, 3, 'ACTIVE', 'ROTE_MEMORY', true),
('CHEM_023', 'Halogens', 'CHEMISTRY', 0.50, 8, 2.0, 5, 'ACTIVE', 'APPLICATION', true),
('CHEM_024', 'Noble Gases', 'CHEMISTRY', 0.35, 4, 1.0, 2, 'ACTIVE', 'ROTE_MEMORY', true),
('CHEM_025', 'd-Block Elements (Transition Metals)', 'CHEMISTRY', 0.60, 10, 3.0, 6, 'ACTIVE', 'CRITICAL_THINKING', true),
('CHEM_026', 'Coordination Compounds', 'CHEMISTRY', 0.65, 12, 3.0, 6, 'ACTIVE', 'CRITICAL_THINKING', true),
('CHEM_027', 'Crystal Field Theory', 'CHEMISTRY', 0.60, 10, 2.0, 4, 'ACTIVE', 'CRITICAL_THINKING', true),
('CHEM_028', 'Metallurgy', 'CHEMISTRY', 0.45, 6, 2.0, 4, 'ACTIVE', 'APPLICATION', true),
('CHEM_029', 'f-Block Elements (Lanthanides)', 'CHEMISTRY', 0.45, 6, 1.0, 2, 'ACTIVE', 'APPLICATION', true),
('CHEM_030', 'Extraction of Metals', 'CHEMISTRY', 0.50, 8, 2.0, 4, 'ACTIVE', 'APPLICATION', true),
('CHEM_031', 'Qualitative Analysis', 'CHEMISTRY', 0.55, 9, 2.0, 4, 'ACTIVE', 'CRITICAL_THINKING', true),
('CHEM_032', 'Surface Chemistry', 'CHEMISTRY', 0.45, 6, 0.0, 0, 'NEP_REMOVED', NULL, true),
('CHEM_033', 'Colloidal Solutions', 'CHEMISTRY', 0.40, 5, 1.0, 2, 'ACTIVE', 'ROTE_MEMORY', true),
('CHEM_034', 'Polymers & Everyday Chemistry', 'CHEMISTRY', 0.40, 5, 0.0, 0, 'NEP_REMOVED', NULL, true),
('CHEM_035', 'Organometallics', 'CHEMISTRY', 0.55, 9, 1.0, 2, 'ACTIVE', 'CRITICAL_THINKING', true),
('CHEM_036', 'General Organic Chemistry', 'CHEMISTRY', 0.50, 8, 2.0, 5, 'ACTIVE', 'APPLICATION', true),
('CHEM_037', 'Nomenclature', 'CHEMISTRY', 0.40, 5, 1.0, 2, 'ACTIVE', 'ROTE_MEMORY', true),
('CHEM_038', 'Isomerism', 'CHEMISTRY', 0.55, 9, 2.0, 5, 'ACTIVE', 'CRITICAL_THINKING', true),
('CHEM_039', 'Stereochemistry', 'CHEMISTRY', 0.60, 10, 2.0, 4, 'ACTIVE', 'CRITICAL_THINKING', true),
('CHEM_040', 'Reaction Mechanisms', 'CHEMISTRY', 0.65, 12, 3.0, 6, 'ACTIVE', 'CRITICAL_THINKING', true),
('CHEM_041', 'SN1 & SN2 Mechanisms', 'CHEMISTRY', 0.60, 10, 2.0, 4, 'ACTIVE', 'CRITICAL_THINKING', true),
('CHEM_042', 'Elimination Reactions', 'CHEMISTRY', 0.55, 9, 1.0, 3, 'ACTIVE', 'CRITICAL_THINKING', true),
('CHEM_043', 'Addition Reactions', 'CHEMISTRY', 0.55, 9, 2.0, 4, 'ACTIVE', 'CRITICAL_THINKING', true),
('CHEM_044', 'Alkanes & Alkenes', 'CHEMISTRY', 0.45, 6, 2.0, 5, 'ACTIVE', 'APPLICATION', true),
('CHEM_045', 'Alkynes & Dienes', 'CHEMISTRY', 0.50, 8, 1.0, 2, 'ACTIVE', 'APPLICATION', true),
('CHEM_046', 'Aromatic Compounds', 'CHEMISTRY', 0.55, 9, 3.0, 6, 'ACTIVE', 'CRITICAL_THINKING', true),
('CHEM_047', 'Electrophilic Aromatic Substitution', 'CHEMISTRY', 0.60, 10, 2.0, 4, 'ACTIVE', 'CRITICAL_THINKING', true),
('CHEM_048', 'Alcohols & Phenols', 'CHEMISTRY', 0.50, 8, 2.0, 4, 'ACTIVE', 'APPLICATION', true),
('CHEM_049', 'Ethers & Epoxides', 'CHEMISTRY', 0.50, 8, 1.0, 2, 'ACTIVE', 'APPLICATION', true),
('CHEM_050', 'Carbonyl Compounds', 'CHEMISTRY', 0.60, 10, 3.0, 6, 'ACTIVE', 'CRITICAL_THINKING', true),
('CHEM_051', 'Carboxylic Acids & Derivatives', 'CHEMISTRY', 0.55, 9, 2.0, 4, 'ACTIVE', 'CRITICAL_THINKING', true),
('CHEM_052', 'Amines & Diazonium Salts', 'CHEMISTRY', 0.55, 9, 2.0, 4, 'ACTIVE', 'CRITICAL_THINKING', true),
('CHEM_053', 'Amino Acids & Proteins', 'CHEMISTRY', 0.45, 6, 1.0, 2, 'ACTIVE', 'APPLICATION', true),
('CHEM_054', 'Carbohydrates', 'CHEMISTRY', 0.45, 6, 1.0, 2, 'ACTIVE', 'APPLICATION', true),
('CHEM_055', 'Nucleic Acids', 'CHEMISTRY', 0.45, 6, 1.0, 2, 'ACTIVE', 'APPLICATION', true);

-- Verification: Should have 160 ACTIVE concepts + 5 NEP_REMOVED = 165 total
-- SELECT COUNT(*) as total_concepts FROM concepts;
-- SELECT syllabus_status, COUNT(*) FROM concepts GROUP BY syllabus_status;

COMMIT;
