-- CR-V4 PHASE 1: COMPLETE MISCONCEPTIONS DATABASE - PART 3 (CHEMISTRY)
-- 110+ Expert-Validated Student Misconceptions
-- JEE Mains Experts Team - Based on Real Coaching Experience
-- Version: 2.0 COMPLETE
-- Date: December 8, 2025

-- ============================================================================
-- CHEMISTRY MISCONCEPTIONS (110 Total)
-- Subject Matter Expert: Chemistry Department
-- Source: NTA Pattern Analysis, NCERT, OP Tandon, Coaching Research
-- ============================================================================

INSERT INTO misconceptions (concept_id, misconception_text, correction, recovery_strategy, diagnostic_question, severity_level, common_exam_trap) VALUES

-- PHYSICAL CHEMISTRY - ATOMIC STRUCTURE & BONDING (CHEM_001 to CHEM_006)
('CHEM_001', 'Electrons orbit the nucleus like planets orbit the sun', 'CORRECTION: Electrons exist in probability clouds (orbitals), not fixed orbits', 'Bohr model is useful for H but electrons have wave nature. Orbitals are probability distributions.', 'Do electrons follow specific circular paths?', 'HIGH', true),
('CHEM_001', 'All atoms have the same number of protons and electrons', 'CORRECTION: NEUTRAL atoms have equal protons and electrons. Ions have different numbers.', 'Cations lose electrons (fewer e⁻). Anions gain electrons (more e⁻).', 'How many electrons in Na⁺?', 'HIGH', true),
('CHEM_001', 'Isotopes have different numbers of protons', 'CORRECTION: Isotopes have SAME protons, DIFFERENT neutrons', 'Same element = same protons = same Z. Isotopes differ in mass number A.', 'What is different between C-12 and C-14?', 'HIGH', true),
('CHEM_002', 'Principal quantum number n can be zero', 'CORRECTION: n starts from 1, not zero. n = 1, 2, 3, ...', 'First shell is n = 1 (K shell). n determines size and energy.', 'What is the minimum value of n?', 'HIGH', true),
('CHEM_002', 'Maximum electrons in a shell = 2n', 'CORRECTION: Maximum electrons in shell = 2n²', 'n=1: 2 electrons. n=2: 8 electrons. n=3: 18 electrons.', 'Maximum electrons in M shell (n=3)?', 'HIGH', true),
('CHEM_002', 'Azimuthal quantum number l can equal n', 'CORRECTION: l ranges from 0 to (n-1), never equal to n', 'For n=3: l can be 0, 1, 2 (not 3). l determines orbital shape.', 'For n=2, what are possible l values?', 'HIGH', true),
('CHEM_003', 'Atomic radius always increases down a group', 'CORRECTION: Generally true, but lanthanide contraction affects transition metals', 'Down group: more shells = larger radius. But 4d and 5d elements similar due to f-orbital contraction.', 'Why are Zr and Hf similar in size?', 'MEDIUM', true),
('CHEM_003', 'Electronegativity increases down a group', 'CORRECTION: Electronegativity DECREASES down a group (opposite of atomic radius trend)', 'More shells = more shielding = weaker attraction for electrons.', 'Which is more electronegative: Cl or I?', 'HIGH', true),
('CHEM_004', 'Ionic bonds are always stronger than covalent bonds', 'CORRECTION: Some covalent bonds (like C≡C) are stronger than some ionic bonds', 'Strength depends on charges, sizes, electronegativity difference. Compare case by case.', 'Is C-C bond stronger than Na-Cl bond?', 'HIGH', true),
('CHEM_004', 'Ionic compounds conduct electricity in solid state', 'CORRECTION: Ionic compounds conduct only when molten or dissolved (ions must be mobile)', 'In solid, ions are fixed in lattice. Need molten/aqueous for ion movement.', 'Does solid NaCl conduct electricity?', 'HIGH', true),
('CHEM_004', 'Covalent bonds always share electrons equally', 'CORRECTION: Equal sharing only in NONPOLAR covalent. Polar covalent has unequal sharing.', 'Polar: electrons closer to more electronegative atom. Creates dipole.', 'Is H-Cl bond polar or nonpolar?', 'HIGH', true),
('CHEM_005', 'All sp³ hybridized atoms have tetrahedral geometry', 'CORRECTION: sp³ gives tetrahedral ELECTRON geometry. Molecular geometry depends on lone pairs.', 'NH₃ is sp³ but pyramidal (1 lone pair). H₂O is sp³ but bent (2 lone pairs).', 'What is the shape of NH₃?', 'HIGH', true),
('CHEM_005', 'Hybridization determines bond strength', 'CORRECTION: Hybridization affects bond angle. s-character affects bond length (more s = shorter).', 'sp (50% s) has shorter bonds than sp³ (25% s). But strength is more complex.', 'Which has shorter C-H bonds: CH₄ or C₂H₂?', 'MEDIUM', true),
('CHEM_006', 'Molecular orbital theory contradicts VSEPR', 'CORRECTION: MO and VSEPR are complementary. MO explains bonding, VSEPR predicts geometry.', 'Use VSEPR for shape. Use MO for bond order, magnetism, relative stability.', 'Does O₂ have double bond according to MO theory?', 'MEDIUM', false),
('CHEM_006', 'Bond order = number of bonding electrons', 'CORRECTION: Bond order = (bonding electrons - antibonding electrons)/2', 'Must subtract antibonding electrons. O₂: (8-4)/2 = 2, not 8/2 = 4.', 'What is bond order of O₂?', 'HIGH', true),

-- PHYSICAL CHEMISTRY - THERMODYNAMICS (CHEM_007 to CHEM_009)
('CHEM_007', 'ΔH = ΔU always', 'CORRECTION: ΔH = ΔU + PΔV (at constant pressure). ΔH = ΔU + ΔnRT for gases.', 'Enthalpy includes PV work. For solids/liquids (ΔV ≈ 0): ΔH ≈ ΔU.', 'For reaction with Δngas = 0, is ΔH = ΔU?', 'HIGH', true),
('CHEM_007', 'Exothermic reactions are always spontaneous', 'CORRECTION: Spontaneity depends on ΔG = ΔH - TΔS, not just ΔH', 'Endothermic reactions can be spontaneous if ΔS is large enough (like ice melting).', 'Is ice melting at 25°C spontaneous?', 'HIGH', true),
('CHEM_008', 'Hess Law only works for enthalpy', 'CORRECTION: Hess Law applies to any state function: ΔH, ΔS, ΔG, etc.', 'State functions depend only on initial and final states, not path.', 'Can you use Hess Law for ΔS calculations?', 'MEDIUM', true),
('CHEM_009', 'Entropy always increases in any reaction', 'CORRECTION: ΔS_universe ≥ 0, but ΔS_system can be negative', 'System entropy can decrease if surroundings entropy increases more.', 'When gas condenses to liquid, does system entropy increase?', 'HIGH', true),
('CHEM_009', 'ΔG = 0 means no reaction occurs', 'CORRECTION: ΔG = 0 means equilibrium. Both forward and reverse reactions occur at equal rates.', 'At equilibrium, no NET change, but reactions still happening.', 'At equilibrium, is the reaction stopped?', 'HIGH', true),

-- PHYSICAL CHEMISTRY - EQUILIBRIUM (CHEM_010 to CHEM_014)
('CHEM_010', 'Equilibrium means reaction has stopped', 'CORRECTION: Equilibrium is DYNAMIC - forward and reverse rates are equal but reactions continue', 'Reaction never stops. Concentrations are constant because rates are equal.', 'At equilibrium, are molecules still reacting?', 'HIGH', true),
('CHEM_010', 'Adding catalyst changes equilibrium constant', 'CORRECTION: Catalyst speeds up reaching equilibrium, does NOT change K', 'Catalyst lowers activation energy equally for forward and reverse reactions.', 'If you add catalyst, does Keq change?', 'HIGH', true),
('CHEM_010', 'Kp = Kc always', 'CORRECTION: Kp = Kc(RT)^Δn where Δn = moles gaseous products - moles gaseous reactants', 'Only when Δn = 0 does Kp = Kc.', 'For N₂ + 3H₂ ⇌ 2NH₃, is Kp = Kc?', 'HIGH', true),
('CHEM_011', 'Weak acids dont dissociate', 'CORRECTION: Weak acids partially dissociate. Strong acids dissociate completely.', 'CH₃COOH ⇌ CH₃COO⁻ + H⁺ (equilibrium exists). HCl → H⁺ + Cl⁻ (complete).', 'Does acetic acid produce any H⁺ ions?', 'HIGH', true),
('CHEM_011', 'pH + pOH = 14 only at 25°C', 'CORRECTION: pH + pOH = pKw. At 25°C, Kw = 10⁻¹⁴, so pKw = 14. At other temps, different.', 'Kw increases with temperature (more auto-ionization). pKw decreases.', 'At 50°C, is pH + pOH still 14?', 'MEDIUM', true),
('CHEM_012', 'pH 7 always means neutral', 'CORRECTION: pH 7 is neutral only at 25°C. At other temperatures, neutral pH differs.', 'Neutral means [H⁺] = [OH⁻]. At higher T, both increase, neutral pH < 7.', 'Is pure water at 50°C acidic because pH < 7?', 'MEDIUM', true),
('CHEM_012', 'Strong acid with pH 1 is more acidic than weak acid with pH 1', 'CORRECTION: Same pH means same [H⁺], so same acidity for the solution', 'pH indicates [H⁺] concentration. Source of H⁺ doesnt matter for acidity.', 'Which is more acidic: 0.1M HCl or solution with pH 1?', 'MEDIUM', true),
('CHEM_013', 'Buffer can resist any amount of acid/base', 'CORRECTION: Buffer has limited capacity. Adding too much acid/base overwhelms it.', 'Buffer works until weak acid or conjugate base is exhausted.', 'Can buffer maintain pH if 1M NaOH is added to 0.1M buffer?', 'HIGH', true),
('CHEM_013', 'Equal concentrations give best buffer', 'CORRECTION: Best buffer is when [acid] = [conjugate base] (at half-equivalence point)', 'At this point, pH = pKa and buffer capacity is maximum.', 'At what point is buffer most effective?', 'MEDIUM', true),
('CHEM_014', 'Ksp indicates how much salt dissolves in grams', 'CORRECTION: Ksp is in terms of molar concentrations. Convert using molar mass.', 'Ksp = [cation]^m[anion]^n. Different compounds have different formulas.', 'Which is more soluble: Ksp = 10⁻⁵ for AB or 10⁻⁶ for A₂B?', 'HIGH', true),
('CHEM_014', 'Common ion always decreases solubility', 'CORRECTION: Common ion decreases solubility (Le Chateliers), but complex formation can increase it', 'AgCl in NaCl: less soluble. AgCl in ammonia: more soluble (complex forms).', 'Does AgCl dissolve more in water or in NH₃?', 'MEDIUM', true),

-- PHYSICAL CHEMISTRY - ELECTROCHEMISTRY (CHEM_015 to CHEM_018)
('CHEM_015', 'Oxidation means gaining oxygen', 'CORRECTION: Modern definition: Oxidation = loss of electrons. Reduction = gain of electrons.', 'OIL RIG: Oxidation Is Loss, Reduction Is Gain (of electrons).', 'In Na → Na⁺ + e⁻, is Na oxidized or reduced?', 'HIGH', true),
('CHEM_015', 'Oxidation number can be a fraction', 'CORRECTION: Yes! Average oxidation number can be fractional (like O in O₃, Fe in Fe₃O₄).', 'Fe₃O₄: O is -2, so 4(-2) = -8. Total Fe = +8, average per Fe = 8/3.', 'What is oxidation state of Fe in Fe₃O₄?', 'MEDIUM', true),
('CHEM_016', 'In galvanic cell, electrons flow from cathode to anode', 'CORRECTION: Electrons flow from ANODE to CATHODE (oxidation at anode, reduction at cathode)', 'Anode = oxidation = electrons released. Cathode = reduction = electrons consumed.', 'In Daniell cell, which electrode loses mass?', 'HIGH', true),
('CHEM_016', 'Higher reduction potential means better reducing agent', 'CORRECTION: LOWER (more negative) reduction potential means better reducing agent', 'Good reducing agents are easily oxidized. They have low reduction potential.', 'Is Li or Au a better reducing agent?', 'HIGH', true),
('CHEM_016', 'E° cell = E° cathode + E° anode', 'CORRECTION: E° cell = E° cathode - E° anode (subtract, not add)', 'Convention: both as reduction potentials. Cell EMF = cathode - anode.', 'If E°Zn = -0.76V, E°Cu = +0.34V, what is E°cell for Zn|Cu?', 'HIGH', true),
('CHEM_017', 'All metals corrode equally', 'CORRECTION: Corrosion depends on position in electrochemical series and conditions', 'More reactive metals corrode easier. Au, Pt resistant. Fe rusts in moist air.', 'Why doesnt gold corrode?', 'MEDIUM', false),
('CHEM_018', 'Faster reactions have higher activation energy', 'CORRECTION: LOWER activation energy = faster reaction (more molecules have enough energy)', 'Ea is energy barrier. Lower barrier = easier to overcome = faster reaction.', 'Do catalysts increase or decrease Ea?', 'HIGH', true),
('CHEM_018', 'Rate constant k depends on concentration', 'CORRECTION: k depends only on temperature (Arrhenius equation). Rate depends on concentration.', 'k = Ae^(-Ea/RT). Rate = k[A]^n. Concentration affects rate, not k.', 'Does doubling concentration change k?', 'HIGH', true),
('CHEM_018', 'Order of reaction equals stoichiometric coefficient', 'CORRECTION: Order is EXPERIMENTALLY determined. May or may not equal coefficients.', 'For A + 2B → products, rate could be k[A][B] or k[A]² etc. Must measure.', 'Can order of reaction be fractional?', 'HIGH', true),

-- INORGANIC CHEMISTRY (CHEM_019 to CHEM_035)
('CHEM_019', 'All Group 1 elements react similarly', 'CORRECTION: Reactivity increases down the group. Li is least reactive, Cs most.', 'Going down: larger atom, easier to lose electron, more reactive.', 'Does Na or K react more vigorously with water?', 'HIGH', true),
('CHEM_019', 'Li is typical alkali metal', 'CORRECTION: Li shows ANOMALOUS behavior due to small size (diagonal relationship with Mg)', 'Li forms covalent compounds, hard carbonate, less soluble sulfate - like Mg.', 'Why is LiCl covalent but NaCl ionic?', 'MEDIUM', true),
('CHEM_020', 'All p-block elements are nonmetals', 'CORRECTION: p-block has metals (Al, Sn, Pb), metalloids (Si, Ge), and nonmetals (N, O)', 'Character changes from metallic (left) to nonmetallic (right) across period.', 'Is lead a metal or nonmetal?', 'HIGH', true),
('CHEM_021', 'Sodium burns with blue flame', 'CORRECTION: Sodium burns with characteristic YELLOW flame (due to 589nm emission)', 'Each element has unique flame color: Na-yellow, K-lilac, Ca-brick red, Cu-green.', 'What color flame does sodium produce?', 'HIGH', true),
('CHEM_022', 'Mg(OH)₂ is a strong base', 'CORRECTION: Mg(OH)₂ is WEAK base (sparingly soluble). NaOH, KOH are strong.', 'Weak base = partially dissociates. Mg(OH)₂ also called Milk of Magnesia.', 'Is Mg(OH)₂ soluble in water?', 'MEDIUM', true),
('CHEM_023', 'Fluorine is the most electronegative and most reactive', 'CORRECTION: Most electronegative yes, but Cl is sometimes more reactive due to F-F weak bond', 'F₂ bond is weak (lone pair repulsion). Some reactions favor Cl₂.', 'Why is F-F bond weaker than Cl-Cl?', 'MEDIUM', true),
('CHEM_024', 'Noble gases form no compounds', 'CORRECTION: Heavier noble gases (Xe, Kr) form compounds: XeF₂, XeF₄, XeF₆', 'Larger atoms have more shells, electrons less tightly held. Can form bonds.', 'Does xenon form any compounds?', 'HIGH', true),
('CHEM_025', 'All transition metals are colored', 'CORRECTION: Compounds with unpaired d electrons are colored. d⁰ and d¹⁰ are colorless.', 'Color requires d-d transitions. Cu²⁺ (d⁹) colored, Cu⁺ (d¹⁰) colorless.', 'Is Zn²⁺ colored or colorless?', 'HIGH', true),
('CHEM_025', 'Transition metals always show +2 oxidation state', 'CORRECTION: Not always. Sc shows +3, Cu shows +1 and +2, etc.', 'Common oxidation states vary. Many show multiple oxidation states.', 'What is the most common oxidation state of Sc?', 'MEDIUM', true),
('CHEM_026', 'All complex compounds are colored', 'CORRECTION: Color depends on d-d transitions. d⁰ and d¹⁰ complexes are colorless.', '[Zn(NH₃)₄]²⁺ is colorless (d¹⁰). [Cu(H₂O)₆]²⁺ is blue (d⁹).', 'Is [Zn(NH₃)₄]²⁺ colored?', 'HIGH', true),
('CHEM_026', 'Coordination number = number of ligands', 'CORRECTION: Coordination number = number of DONOR ATOMS, not ligands', 'Bidentate ligand like en (ethylenediamine) contributes 2 to coordination number.', 'What is CN of [Co(en)₃]³⁺?', 'HIGH', true),
('CHEM_027', 'Crystal field theory explains everything about coordination compounds', 'CORRECTION: CFT is a model. It explains color, magnetism but has limitations (covalency ignored).', 'CFT treats bonding as purely electrostatic. Ligand field theory is more complete.', 'Does CFT account for covalent bonding?', 'MEDIUM', false),
('CHEM_028', 'Ores are always oxides', 'CORRECTION: Ores can be oxides, sulfides, carbonates, halides, etc.', 'Haematite (Fe₂O₃), Galena (PbS), Limestone (Cite), Cryolite (AlF₃).', 'What type of ore is galena (PbS)?', 'MEDIUM', true),
('CHEM_029', 'Lanthanides and actinides have identical properties', 'CORRECTION: Actinides show more variable oxidation states and are radioactive', 'Lanthanides: mostly +3. Actinides: +3 to +6 common. All actinides radioactive.', 'Are all lanthanum compounds radioactive?', 'MEDIUM', false),
('CHEM_030', 'Electrolysis always produces pure metal', 'CORRECTION: Electrolysis gives pure metal only with proper conditions (electrolyte, electrodes)', 'Impurities can deposit. Refining may need multiple steps.', 'How is copper purified electrolytically?', 'MEDIUM', false),
('CHEM_031', 'All cations give precipitates with NaOH', 'CORRECTION: Many cations give precipitates, but Al³⁺, Zn²⁺, Pb²⁺ precipitates dissolve in excess NaOH', 'Amphoteric hydroxides dissolve in both acid and excess base.', 'What happens when excess NaOH is added to Al(OH)₃?', 'HIGH', true),
('CHEM_033', 'Colloids are same as solutions', 'CORRECTION: Colloids have particles (1-1000nm) larger than true solutions but smaller than suspensions', 'Colloids show Tyndall effect, Brownian motion. Solutions do not.', 'Does milk show Tyndall effect?', 'MEDIUM', true),
('CHEM_035', 'Organometallic compounds have only metal-carbon bonds', 'CORRECTION: Must have at least one direct metal-carbon bond, may have other bonds too', 'Ferrocene, Grignard reagent (RMgX), Zeise salt all are organometallics.', 'Is CH₃MgBr organometallic?', 'MEDIUM', false),

-- ORGANIC CHEMISTRY (CHEM_036 to CHEM_055)
('CHEM_036', 'All carbon compounds are organic', 'CORRECTION: Carbonates, cyanides, carbides, oxides of C are considered inorganic', 'Organic chemistry studies hydrocarbons and their derivatives.', 'Is Na₂CO₃ organic or inorganic?', 'HIGH', true),
('CHEM_036', 'Organic reactions are always slow', 'CORRECTION: Many organic reactions are fast (acid-base, some free radical reactions)', 'Speed depends on mechanism, activation energy, conditions.', 'Are all combustion reactions slow?', 'MEDIUM', false),
('CHEM_037', 'In IUPAC naming, longest chain always starts from one end', 'CORRECTION: Longest chain gives lowest locants to substituents (may start from either end)', 'Number from end that gives lower numbers to substituents.', 'Name: CH₃-CH(CH₃)-CH₂-CH₃', 'HIGH', true),
('CHEM_038', 'Structural isomers have same properties', 'CORRECTION: Structural isomers have different physical and chemical properties', 'n-butane and isobutane have different boiling points, density.', 'Do n-pentane and isopentane have same boiling point?', 'HIGH', true),
('CHEM_038', 'All isomers have same molecular formula', 'CORRECTION: Correct! Isomers must have same molecular formula but different arrangement.', 'This is the definition of isomers. Different formulas = different compounds.', 'Are C₂H₆O isomers always alcohols?', 'MEDIUM', true),
('CHEM_039', 'Optical isomers are always mirror images', 'CORRECTION: Enantiomers are mirror images. Diastereomers are stereoisomers that arent.', 'Chiral compounds with multiple stereocenters can have diastereomers.', 'Can a compound with 2 chiral centers have a meso form?', 'HIGH', true),
('CHEM_039', 'All chiral molecules rotate plane of polarized light in same direction', 'CORRECTION: Enantiomers rotate in OPPOSITE directions (+ and -)', 'R and S configurations dont directly tell rotation direction.', 'Do D and L glucose rotate light the same direction?', 'HIGH', true),
('CHEM_040', 'Carbocations are always unstable', 'CORRECTION: Stability varies: tertiary > secondary > primary > methyl', 'Hyperconjugation and inductive effect stabilize carbocations.', 'Which is more stable: CH₃⁺ or (CH₃)₃C⁺?', 'HIGH', true),
('CHEM_040', 'All SN2 reactions invert stereochemistry', 'CORRECTION: Correct! SN2 ALWAYS inverts (Walden inversion). SN1 can racemize.', 'SN2: backside attack causes inversion. SN1: planar carbocation attacked from both sides.', 'Does SN1 always invert configuration?', 'HIGH', true),
('CHEM_041', 'SN1 and SN2 have same rate law', 'CORRECTION: SN1: Rate = k[R-X]. SN2: Rate = k[R-X][Nu⁻]. Different orders.', 'SN1 is unimolecular (RDS is ionization). SN2 is bimolecular.', 'How does SN2 rate change if nucleophile concentration doubles?', 'HIGH', true),
('CHEM_041', 'Good leaving group means strong nucleophile', 'CORRECTION: Good leaving groups are weak bases (stable after leaving). Often opposite of nucleophiles.', 'I⁻ is good leaving group (stable) but Cl⁻ is stronger nucleophile.', 'Is OH⁻ a good leaving group?', 'HIGH', true),
('CHEM_042', 'E1 and E2 always give same product', 'CORRECTION: E1 follows Zaitsev (more substituted). E2 requires anti-periplanar geometry.', 'E2 needs specific geometry. E1 forms most stable alkene.', 'Why might E1 and E2 give different products?', 'MEDIUM', true),
('CHEM_043', 'Markovnikov rule means H goes to carbon with fewer H', 'CORRECTION: Markovnikov: H goes to carbon with MORE H atoms already (more substituted C gets electrophile)', 'In HBr + propene: H to C1 (more H), Br to C2 (more substituted).', 'Predict major product: HBr + CH₃CH=CH₂', 'HIGH', true),
('CHEM_044', 'Alkanes are completely unreactive', 'CORRECTION: Alkanes undergo combustion, halogenation (with UV), and pyrolysis', 'Low reactivity due to strong C-H and C-C bonds, but reactions exist.', 'Can methane react with Cl₂?', 'MEDIUM', true),
('CHEM_045', 'Triple bonds are more reactive than double bonds', 'CORRECTION: Generally alkynes are less reactive than alkenes toward addition (electron density different)', 'Both undergo addition, but triple bond has different regioselectivity.', 'In electrophilic addition, which reacts faster: alkene or alkyne?', 'MEDIUM', true),
('CHEM_046', 'Benzene reacts like alkenes', 'CORRECTION: Benzene is unusually stable due to aromaticity. Prefers SUBSTITUTION over addition.', 'Resonance energy stabilizes benzene. Addition would destroy aromaticity.', 'Why doesnt benzene undergo addition with Br₂?', 'HIGH', true),
('CHEM_046', 'All rings are aromatic', 'CORRECTION: Hückels rule: 4n+2 π electrons, planar, cyclic, fully conjugated for aromaticity', 'Cyclooctatetraene is not aromatic (8 π electrons = 4n, antiaromatic if planar).', 'Is cyclobutadiene aromatic?', 'HIGH', true),
('CHEM_047', 'All substituents are ortho-para directors', 'CORRECTION: Activating groups are o,p-directing. Deactivating (except halogens) are meta-directing.', '-NO₂, -CHO, -COOH are meta directors. -OH, -NH₂, -CH₃ are o,p directors.', 'Where does -NO₂ group direct incoming electrophile?', 'HIGH', true),
('CHEM_048', 'All alcohols are soluble in water', 'CORRECTION: Lower alcohols soluble. Higher alcohols less soluble (hydrocarbon part dominates).', 'Methanol, ethanol soluble. Butanol: slightly. Decanol: insoluble.', 'Is 1-decanol soluble in water?', 'MEDIUM', true),
('CHEM_048', 'Phenol is a weaker acid than alcohol', 'CORRECTION: Phenol is MORE acidic than alcohols (resonance stabilization of phenoxide ion)', 'Phenoxide is stabilized by delocalization. Alkoxide is not.', 'Which is more acidic: ethanol or phenol?', 'HIGH', true),
('CHEM_049', 'Ethers are very reactive', 'CORRECTION: Ethers are relatively inert. Used as solvents due to low reactivity.', 'C-O-C bond is stable. Cleaved only by strong acids (HI, HBr).', 'Can ether be cleaved by NaOH?', 'MEDIUM', true),
('CHEM_050', 'Aldehydes and ketones are equally reactive', 'CORRECTION: Aldehydes are MORE reactive than ketones (steric and electronic factors)', 'Ketones have more steric hindrance and electron-donating groups.', 'Which reacts faster with HCN: HCHO or CH₃COCH₃?', 'HIGH', true),
('CHEM_050', 'All carbonyl compounds give Tollens test', 'CORRECTION: Only ALDEHYDES give Tollens test (silver mirror). Ketones do not.', 'Tollens test = oxidation. Aldehydes can be oxidized to acids. Ketones cannot.', 'Does acetone give silver mirror test?', 'HIGH', true),
('CHEM_051', 'All carboxylic acids are strong acids', 'CORRECTION: Carboxylic acids are WEAK acids (pKa ~ 4-5). HCl, H₂SO₄ are strong.', 'Partial ionization. Resonance stabilizes conjugate base but still weak.', 'Is acetic acid a strong or weak acid?', 'HIGH', true),
('CHEM_051', 'Acid chlorides and anhydrides react similarly', 'CORRECTION: Acid chlorides are MORE reactive than anhydrides', 'Reactivity order: Acid chlorides > anhydrides > esters > amides.', 'Which reacts faster with water: CH₃COCl or (CH₃CO)₂O?', 'MEDIUM', true),
('CHEM_052', 'All amines are bases of equal strength', 'CORRECTION: Basicity: R₂NH > RNH₂ > NH₃ > ArNH₂ (aliphatic 2° > 1° > NH₃ > aromatic)', 'Aryl amines weaker due to lone pair delocalization into ring.', 'Is aniline more or less basic than methylamine?', 'HIGH', true),
('CHEM_052', 'Diazonium salts are stable at high temperatures', 'CORRECTION: Diazonium salts are unstable, used immediately. Stable only at 0-5°C.', 'Above 10°C, decomposition occurs. Keep cold for Sandmeyer reactions.', 'At what temperature should diazonium salt be prepared?', 'HIGH', true),
('CHEM_053', 'All amino acids are optically active', 'CORRECTION: Glycine is NOT optically active (no chiral center - two H on alpha carbon)', 'Glycine: H₂N-CH₂-COOH. No asymmetric carbon.', 'Is glycine chiral?', 'HIGH', true),
('CHEM_053', 'Peptide bond forms between -COOH and -COOH groups', 'CORRECTION: Peptide bond forms between -COOH of one amino acid and -NH₂ of another', 'Condensation: -COOH + H₂N- → -CO-NH- + H₂O (amide bond).', 'Which groups form peptide bond?', 'HIGH', true),
('CHEM_054', 'All sugars are reducing sugars', 'CORRECTION: Only sugars with free aldehyde/ketone are reducing. Sucrose is non-reducing.', 'Sucrose: glycosidic bond between C1 and C2 (both anomeric carbons). No free CHO.', 'Is sucrose a reducing sugar?', 'HIGH', true),
('CHEM_054', 'Glucose and fructose have same structure', 'CORRECTION: Glucose is aldose (aldehyde). Fructose is ketose (ketone). Isomers but different.', 'Same formula C₆H₁₂O₆ but different functional group position.', 'What is the difference between glucose and fructose?', 'MEDIUM', true),
('CHEM_055', 'DNA and RNA have same sugar', 'CORRECTION: DNA has deoxyribose. RNA has ribose (extra OH at 2 position).', 'Deoxy = one less oxygen. This affects stability and structure.', 'Which has -OH at 2 position: DNA or RNA?', 'HIGH', true),
('CHEM_055', 'Watson-Crick base pairing: A pairs with G', 'CORRECTION: A pairs with T (or U in RNA). G pairs with C.', 'Complementary pairing: A-T (2 H-bonds), G-C (3 H-bonds).', 'What base pairs with adenine in DNA?', 'HIGH', true);

COMMIT;
